# Analysis

## Setting parameters

In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
from quickrules.data_handling import calculate_score, count_all_rules, count_all_attributes, bold
from pathlib import Path
from quickrules.data_handling import balanced_accuracy_score
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [3]:
data_sets = [
    'australian',
     'automobile',
     'bands',
     'bupa',
     'cleveland',
     'contraceptive',
     'crx',
     'dermatology',
     'ecoli',
     'german',
     'glass',
     'haberman',
     'heart',
     'ionosphere',
     'mammographic',
     'pima',
     'saheart',
     # 'sonar',  # 70 features!
     'spectfheart',
     'vehicle',
     'vowel',
     'wine',
     'winequality-red',
     'wisconsin',
     'yeast'
]

In [4]:
len(data_sets)

24

In [5]:
data_base = Path.cwd() / 'keel-data'
include_sets = data_sets
metric = accuracy_score  # balanced_
scores = {}
rules = {}
attributes = {}
results_base = Path.cwd()

## Loading MODLEM results

In [22]:
weka_folder = Path.cwd() / 'weka_rules_files'
name = 'modlem'
file = 'weka-accuracy.csv'  # 'weka-balanced-accuracy.csv'

In [23]:
scores[name] = pd.read_csv(weka_folder / file, header=None, index_col=0).to_dict()[1]

In [24]:
rules[name] = {}
attributes[name] = {}
for file in weka_folder.iterdir():
    if file.name[-3:] == 'txt':
        short_name = file.name[:-4]
        with open(file, 'r') as f:
            line = f.readline()
            nrs = []
            while len(line) > 4:
                nrs.append(line.count('&') + 1)
                line = f.readline()
        rules[name][short_name] = len(nrs)
        attributes[name][short_name] = np.average(nrs)

## Loading QuickRules results

In [9]:
qr_models = {
    'qr': results_base / 'no-prune-results' / 'close-min-max-combo-results',
    'lin-owa': results_base / 'no-prune-results' / 'rules-lin-owa-qr-combo-minmax-results',
    'trun-lin-owa': results_base / 'no-prune-results' / 'rules-trun-lin-owa-qr-combo-minmax-results',
    'trun-exp-owa': results_base / 'no-prune-results' / 'trun-exp-owa-qr-combo-minmax-results',
    'avg-qr': results_base / 'mon-avg-std-minmax-results-2',
    'avg-lin-owa' : results_base / 'mon-avg-lin-owa-minmax-results-2',
    'prune-qr': results_base / 'prune-results' / 'prune-qr-combo-minmax-results',
    'prune-lin-owa': results_base / 'prune-results' / 'prune-lin-owa-qr-combo-minmax-results',
    'prune-trun-lin-owa': results_base / 'prune-results' / 'prune-trun-lin-owa-qr-combo-min-max-results',
    'prune-trun-exp-owa': results_base / 'prune-results' / 'prune-trun-exp-owa-qr-combo-min-max-results',
    'prune-avg-qr': results_base / 'prune-mon-avg-std-minmax-results-2',
    'prune-avg-lin-owa' : results_base / 'prune-mon-avg-lin-owa-minmax-results-2',
}

In [10]:
for model, path in qr_models.items():
    scores[model] = calculate_score(
        data_folder=data_base,
        results_folder=path,
        include=include_sets,
        metric=metric
    )
    rules[model] = count_all_rules(
        Path.cwd() / results_base / path,
        include=include_sets
    )
    attributes[model] = count_all_attributes(
        Path.cwd() / results_base / path,
        include=include_sets
    )

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/lib/function_base.py:518: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Unsuccessful for fold1 on mammographic.
Unsuccessful for fold2 on mammographic.
Unsuccessful for fold3 on mammographic.
Unsuccessful for fold4 on mammographic.
Unsuccessful for fold5 on mammographic.
Unsuccessful for fold6 on mammographic.
Unsuccessful for fold7 on mammographic.
Unsuccessful for fold8 on mammographic.
Unsuccessful for fold9 on mammographic.
Unsuccessful for fold10 on mammographic.

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/lib/function_base.py:518: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Unsuccessful for fold1 on mammographic.
Unsuccessful for fold2 on mammographic.
Unsuccessful for fold3 on mammographic.
Unsuccessful for fold4 on mammographic.
Unsuccessful for fold5 on mammographic.
Unsuccessful for fold6 on mammographic.
Unsuccessful for fold7 on mammographic.
Unsuccessful for fold8 on mammographic.
Unsuccessful for fold9 on mammographic.
Unsuccessful for fold10 on mammographic.

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/lib/function_base.py:518: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/lib/function_base.py:518: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

## Adding results for non rule based models

In [11]:
other_models =  {
    'naive-bayes': Path.cwd() / 'NaiveBayes-results',
    'svm': Path.cwd() / 'svm',
    'tree': Path.cwd() / 'decision-tree'
}

In [12]:
for model, path in other_models.items():
    print(model)
    scores[model] = calculate_score(
        data_folder=data_base,
        results_folder=path,
        include=include_sets,
        metric=metric,
        verbose=False
    )

naive-bayes
svm
tree

In [13]:
frnn_results = pd.read_csv(Path.cwd() / 'frnn_new_results.csv', header=None, index_col=0).to_dict()[1]
scores['frnn'] =  {data_set: frnn_results[data_set] for data_set in include_sets}

## Tables
set 1 = QR + OWA-variants without pruning
set 2 = focus on pruning

In [25]:
 names = {
    1: [
        'qr',
        'lin-owa',
        'trun-lin-owa',
        'trun-exp-owa',
        'modlem'
    ],
    2: [
        'qr',
        'lin-owa',
        'prune-qr',
        'prune-lin-owa'
    ],
    3: [
        'qr',
        'lin-owa',
        'avg-qr',
        'avg-lin-owa'
    ],
    4: [
        'lin-owa',
        'modlem'
    ],
    5: [
        'lin-owa',
        'frnn',
        'svm',
        'naive-bayes',
        'tree',
    ]
}

In [26]:
nr = 1

In [27]:
main_folder = 'normal_acc'

In [28]:
table_acc = pd.DataFrame(index=data_sets, columns=names[nr])

In [29]:
for model in names[nr]:
    for data_set, score in scores[model].items():
        table_acc.loc[data_set, model] = score

In [30]:
table_acc.loc['mean'] = table_acc.mean(axis='rows', skipna=True)

In [31]:
table_acc

                       qr   lin-owa trun-lin-owa trun-exp-owa    modlem
australian       0.857971  0.850725     0.855072     0.857971    0.8565
automobile       0.714651  0.690826     0.690826     0.690826    0.8046
bands            0.633694  0.640524      0.63242     0.631979    0.6875
bupa             0.578924  0.576067     0.576067     0.578924    0.6785
cleveland        0.542211  0.546343     0.553124     0.539323    0.5522
contraceptive    0.455589  0.444029     0.449402     0.450083    0.5133
crx              0.548192  0.551316     0.552952     0.551339    0.8515
dermatology      0.576909  0.890847     0.718861     0.732083    0.9498
ecoli             0.42852  0.440374     0.425579     0.425579    0.7738
german              0.682     0.682        0.682        0.682     0.741
glass            0.478825  0.451791     0.487957     0.485192     0.659
haberman         0.735269  0.738602     0.738602     0.738602    0.6804
heart            0.792593  0.788889     0.788889     0.792593    0.7667
ionosphere       0.755238  0.749603     0.749603     0.749603    0.9174
mammographic     0.520518  0.782981     0.786584     0.791292     0.812
pima             0.652397  0.653713     0.652397     0.652397    0.7617
saheart          0.519149  0.519149     0.519149     0.519149    0.6517
spectfheart      0.801425  0.790456      0.78661      0.79416    0.8165
vehicle          0.384202  0.442269     0.456471     0.455336    0.7377
vowel            0.162626  0.411111     0.285859     0.283838    0.6838
wine             0.920588  0.826471     0.820261     0.831373    0.9608
winequality-red  0.462158  0.451533     0.444658     0.444658      0.66
wisconsin        0.948984  0.959129     0.962007     0.960579     0.968
yeast            0.350413   0.34566     0.345678     0.342314    0.5566
mean             0.604294   0.63435     0.623376     0.624216  0.751708

In [108]:
bolded_first = table_acc.apply(lambda data: bold(data), axis=1)
bolded_first.to_latex(buf= Path.cwd() / 'tables' / main_folder / f'tab{nr}acc.txt', escape=False)

/var/folders/_f/yf3dkr5x1397v4ntwhncxfhw0000gn/T/ipykernel_75174/2435143101.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  bolded_first.to_latex(buf= Path.cwd() / 'tables' / f'tab{nr}acc.txt', escape=False)

In [92]:
table_rule = pd.DataFrame(index=data_sets, columns=names[nr])
for model in names[nr]:
    for data_set, rule_count in rules[model].items():
        table_rule.loc[data_set, model] = rule_count
table_rule.loc['mean'] = table_rule.mean(axis='rows', skipna=True)

In [93]:
table_rule

                    lin-owa      modlem
australian            426.4         121
automobile             75.9          35
bands                 327.5         113
bupa                  307.1         103
cleveland             201.1          95
contraceptive        1225.4         488
crx                   586.9         110
dermatology           227.9          27
ecoli                 302.4          56
german                839.3         251
glass                 191.8          50
haberman              256.9          90
heart                 149.1          62
ionosphere            282.7          30
mammographic          466.1         138
pima                  691.2         191
saheart               324.0         138
spectfheart           240.1          55
vehicle               761.4         177
vowel                 891.0         200
wine                  160.2          13
winequality-red      1243.0         376
wisconsin             312.6          31
yeast                1308.9         337
mean             491.620833  136.958333

In [94]:
bolded_first = table_rule.apply(lambda data: bold(data, optimum='min', format_string="%.1f"), axis=1)
bolded_first.to_latex(buf= Path.cwd() / 'tables' / f'tab{nr}rules.txt', escape=False)

/var/folders/_f/yf3dkr5x1397v4ntwhncxfhw0000gn/T/ipykernel_75174/1511408646.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  bolded_first.to_latex(buf= Path.cwd() / 'tables' / f'tab{nr}rules.txt', escape=False)

In [95]:
table_attribute = pd.DataFrame(index=data_sets, columns=names[nr])
for model in names[nr]:
    for data_set, attribute_count in attributes[model].items():
        table_attribute.loc[data_set, model] = attribute_count
table_attribute.loc['mean'] = table_attribute.mean(axis='rows', skipna=True)

In [96]:
table_attribute

                   lin-owa    modlem
australian        8.451909  2.355372
automobile        3.387946  1.942857
bands            17.284414  2.106195
bupa              5.880744  2.194175
cleveland         9.084441  2.589474
contraceptive     8.748066  3.901639
crx                5.52939  2.463636
dermatology       18.81397  2.555556
ecoli             5.928905  2.339286
german             1.05207  2.920319
glass             8.220546       2.1
haberman          2.992995  2.255556
heart             8.046704  2.209677
ionosphere       29.464583  1.533333
mammographic       4.81365  2.775362
pima              7.947912  2.073298
saheart           1.876506  1.862319
spectfheart      29.626455  1.745455
vehicle          15.195562   2.60452
vowel            11.708193      2.15
wine             11.645435  1.461538
winequality-red  10.961717  2.805851
wisconsin         7.092027  2.225806
yeast             7.928891   3.25816
mean             10.070126  2.351224

In [97]:
bolded_first = table_attribute.apply(lambda data: bold(data, optimum='min'), axis=1)
bolded_first.to_latex(buf= Path.cwd() / 'tables' / f'tab{nr}atts.txt', escape=False)

/var/folders/_f/yf3dkr5x1397v4ntwhncxfhw0000gn/T/ipykernel_75174/12819971.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  bolded_first.to_latex(buf= Path.cwd() / 'tables' / f'tab{nr}atts.txt', escape=False)