# Analysis

In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
from quickrules.data_handling import calculate_score, count_all_rules
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, accuracy_score
import pandas as pd

In [6]:
data_sets = [
    'australian',  # temp disable because of mismatched labels in pred and true
    'cleveland',
    'glass',
    'heart',
    'ionosphere',
    'pima',
    'wine',
    'bupa',
    'saheart',
    'wisconsin',
    'crx',
    'ecoli',
    'haberman',
    # 'mammographic', # for prune-qr no result weirdly
    'automobile',
    # 'bands',
    # 'contraceptive',
    # 'german',
    # 'movement',
    # 'sonar',
    # 'spectfheart',
    # 'vehicle',
    # 'vowel',
    # 'winequality-red',
    # 'yeast'
]

other_datasets = [
    # 'banana',
    # 'dermatology',
    # 'page-blocks',
    # 'phoneme',
    # 'ring',
    # 'satimage',
    # 'segment',
    # 'marketing',
    # 'texture',
    # 'titanic',
    # 'thyroid',
    # 'twonorm',
    # 'wdbc',
    # 'winequality-white',
    # 'spambase',
]

In [7]:
len(data_sets)

13

In [39]:
results_base = Path.cwd()

models = {
    # 'naive-bayes': 'NB-results',
    'qr': results_base / 'no-prune-results' / 'close-min-max-combo-results',
    'lin-owa': results_base / 'no-prune-results' / 'rules-lin-owa-qr-combo-minmax-results',
    'trun-lin-owa': results_base / 'no-prune-results' / 'rules-trun-lin-owa-qr-combo-minmax-results',
    'trun-exp-owa': results_base / 'no-prune-results' / 'trun-exp-owa-qr-combo-minmax-results',
    'avg-qr': results_base / 'avg-std-minmax-results',
    'avg-lin-owa' : results_base / 'avg-lin-owa-minmax-results',
    'prune-qr': results_base / 'prune-results' / 'prune-qr-combo-minmax-results',
    'prune-lin-owa': results_base / 'prune-results' / 'prune-lin-owa-qr-combo-minmax-results',
    'prune-trun-lin-owa': results_base / 'prune-results' / 'prune-trun-lin-owa-qr-combo-min-max-results',
    'prune-trun-exp-owa': results_base / 'prune-results' / 'prune-trun-exp-owa-qr-combo-min-max-results',
    'prune-avg-qr': results_base / 'prune-avg-std-minmax-results',
    'prune-avg-lin-owa' : results_base / 'prune-avg-lin-owa-minmax-results',

}

In [40]:
data_base = Path.cwd() / 'keel-data'
metric = balanced_accuracy_score
scores = {}
rules = {}

for model, path in models.items():
    scores[model] = calculate_score(
        data_folder=data_base,
        results_folder=path,
        include=data_sets,
        metric=metric
    )
    if model != 'naive-bayes':
        rules[model] = count_all_rules(
            Path.cwd() / results_base / path,
            include=data_sets
        )

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Unsuccessful for fold1 on saheart.
Unsuccessful for fold2 on saheart.
Unsuccessful for fold3 on saheart.
Unsuccessful for fold4 on saheart.
Unsuccessful for fold5 on saheart.
Unsuccessful for fold6 on saheart.
Unsuccessful for fold7 on saheart.
Unsuccessful for fold8 on saheart.
Unsuccessful for fold9 on saheart.
Unsuccessful for fold10 on saheart.
Unsuccessful for fold1 on heart.
Unsuccessful for fold2 on heart.
Unsuccessful for fold3 on heart.
Unsuccessful for fold4 on heart.
Unsuccessful for fold5 on heart.
Unsuccessful for fold6 on heart.
Unsuccessful for fold7 on heart.
Unsuccessful for fold8 on heart.
Unsuccessful for fold9 on heart.
Unsuccessful for fold10 on heart.
Unsuccessful for fold1 on australian.
Unsuccessful for fold2 on australian.
Unsuccessful for fold3 on australian.
Unsuccessful for fold4 on australian.
Unsuccessful for fold5 on australian.
Unsuccessful for fold6 on australian.
Unsuccessful for fold7 on australian.
Unsuccessful for fold8 on australian.
Unsuccessful for fold9 on australian.
Unsuccessful for fold10 on australian.

ValueError: Mix of label input types (string and number)

In [33]:
name = 'non-overlap-rules'
scores[name] = calculate_score(
    data_folder=data_base,
    results_folder=results_base / name,
    include=data_sets,
    metric=metric,
    label_encoding=True
)
rules[name] = count_all_rules(
            Path.cwd() / results_base / name,
            include=data_sets
        )

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:2184: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

In [34]:
df = pd.DataFrame(index=data_sets, columns=scores.keys())

In [35]:
for model, score_dict in scores.items():
    for data_set, score in score_dict.items():
        df.loc[data_set, model] = score

In [36]:
df

,qr,lin-owa,trun-lin-owa,trun-exp-owa,prune-qr,prune-lin-owa,prune-trun-lin-owa,prune-trun-exp-owa,non-overlap-rules
australian,0.865348,0.856859,0.860529,0.863444,0.863735,0.858174,0.860529,0.863444,0.797795
cleveland,0.208347,0.286954,0.289811,0.282134,0.208347,0.286954,0.289811,0.286134,0.297316
glass,0.31381,0.255853,0.283234,0.286607,0.273512,0.255853,0.267262,0.256944,0.642837
heart,0.785833,0.785,0.786667,0.790833,0.785833,0.789167,0.786667,0.786667,0.759167
ionosphere,0.658974,0.651282,0.651282,0.651282,0.655449,0.651282,0.651282,0.651282,0.881762
pima,0.502775,0.504698,0.502775,0.502775,0.502775,0.504698,0.504627,0.502775,0.648611
wine,0.915873,0.796825,0.793175,0.806508,0.730952,0.796825,0.792063,0.792063,0.927262
bupa,0.5,0.4975,0.4975,0.5,0.5,0.4975,0.4975,0.5,0.642691
saheart,0.571337,0.571337,0.571337,0.571337,0.571337,0.571337,0.571337,0.571337,NaN
wisconsin,0.933215,0.950417,0.954584,0.952501,0.952001,0.948334,0.958751,0.959912,0.95084
crx,0.501797,0.505741,0.507473,0.505688,0.501797,0.505741,0.505688,0.505688,NaN
ecoli,0.17585,0.247619,0.17381,0.17381,0.17381,0.247619,0.17381,0.17381,0.666074
haberman,0.5,0.50625,0.50625,0.50625,0.503706,0.50625,0.50625,0.50625,NaN

In [35]:
# frnn_results = pd.read_csv(Path.cwd() / 'frnn_results.csv', header=None, index_col=0)

In [36]:
# for data_set in df.index.values:
#     df.loc[data_set, 'frnn'] = frnn_results.loc[data_set, 1]

In [37]:
df.loc['mean'] = df.mean(axis='rows', skipna=True)

In [38]:
df

,qr,lin-owa,trun-lin-owa,trun-exp-owa,prune-qr,prune-lin-owa,prune-trun-lin-owa,prune-trun-exp-owa,non-overlap-rules
australian,0.865348,0.856859,0.860529,0.863444,0.863735,0.858174,0.860529,0.863444,0.797795
cleveland,0.208347,0.286954,0.289811,0.282134,0.208347,0.286954,0.289811,0.286134,0.297316
glass,0.31381,0.255853,0.283234,0.286607,0.273512,0.255853,0.267262,0.256944,0.642837
heart,0.785833,0.785,0.786667,0.790833,0.785833,0.789167,0.786667,0.786667,0.759167
ionosphere,0.658974,0.651282,0.651282,0.651282,0.655449,0.651282,0.651282,0.651282,0.881762
pima,0.502775,0.504698,0.502775,0.502775,0.502775,0.504698,0.504627,0.502775,0.648611
wine,0.915873,0.796825,0.793175,0.806508,0.730952,0.796825,0.792063,0.792063,0.927262
bupa,0.5,0.4975,0.4975,0.5,0.5,0.4975,0.4975,0.5,0.642691
saheart,0.571337,0.571337,0.571337,0.571337,0.571337,0.571337,0.571337,0.571337,NaN
wisconsin,0.933215,0.950417,0.954584,0.952501,0.952001,0.948334,0.958751,0.959912,0.95084
crx,0.501797,0.505741,0.507473,0.505688,0.501797,0.505741,0.505688,0.505688,NaN
ecoli,0.17585,0.247619,0.17381,0.17381,0.17381,0.247619,0.17381,0.17381,0.666074
haberman,0.5,0.50625,0.50625,0.50625,0.503706,0.50625,0.50625,0.50625,NaN
mean,0.571782,0.570487,0.567571,0.568705,0.555635,0.570749,0.566583,0.56587,0.721436

In [31]:
rule_df = pd.DataFrame(index=data_sets, columns=rules.keys())
for model, rule_dict in rules.items():
    for data_set, rule_count in rule_dict.items():
        rule_df.loc[data_set, model] = rule_count
rule_df.loc['mean'] = rule_df.mean(axis='rows', skipna=True)

In [32]:
rule_df

,qr,lin-owa,trun-lin-owa,trun-exp-owa,prune-qr,prune-lin-owa,prune-trun-lin-owa,prune-trun-exp-owa,non-overlap-rules
australian,732.2,426.4,606.5,636.3,529.2,400.6,602.7,631.3,105.2
cleveland,331.1,201.1,266.4,268.2,331.1,199.2,265.3,266.4,109.5
glass,225.7,191.8,193.4,193.6,162.0,191.8,189.1,188.8,58.8
heart,303.7,149.1,239.9,241.0,303.7,144.1,239.1,239.2,46.7
ionosphere,460.5,282.7,291.8,295.9,215.3,282.7,275.4,272.6,27.9
pima,824.6,691.2,692.2,691.9,586.1,691.2,688.6,688.9,168.3
wine,211.2,160.2,162.4,162.0,127.4,160.2,158.3,158.6,10.9
bupa,332.4,307.1,310.9,311.3,280.3,307.1,303.3,302.9,104.4
saheart,324.0,324.0,324.0,324.0,324.0,324.0,324.0,324.0,NaN
wisconsin,280.5,312.6,321.9,347.9,101.3,302.6,298.3,289.2,28.2
crx,622.4,586.9,589.7,591.0,546.6,586.9,584.1,582.8,NaN
ecoli,315.0,302.4,308.2,308.2,287.3,302.4,296.6,296.6,75.4
haberman,116.9,256.9,256.3,256.3,87.2,256.9,256.3,256.3,NaN
mean,390.784615,322.492308,351.046154,355.969231,298.576923,319.207692,344.7,345.969231,73.53