In [1]:
%load_ext autoreload
%autoreload 2

# Work risk

In [3]:
from fuzzyroughrules.rule_induction_base import RuleGenerator
from fuzzyroughrules.approximations import LowerApproximation
from fuzzyroughrules.operators import ImplicatorInclusion
from pathlib import Path
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv(Path.cwd() / 'other-data' / 'full-dataset.csv', sep=",")
data

,worker ID,Body part,age,hight,weight,work experince,medical record,Station risk,shift,station,final risk,corrective action,problem,operation,environment,job frequency
0,1,Back,31,175,58,8,0,0.69,1,1,7.75,Hamstring & lumbar stretches,low back pain/sciatica risk,42,49,75
1,1,neck,31,175,58,8,0,0.63,1,1,7.75,Neck side bends,Neck strain,50,38,23
2,1,hand,31,175,58,8,0,0.48,1,1,3.00,wall angels,shoulder tendonitis,41,20,33
3,1,knee,31,175,58,8,0,0.44,1,1,5.00,mini squates,Prolonged standing,15,43,60
4,2,back,32,180,80,8,1,0.69,2,1,8.00,Cat-cow stretch/glute bridge,low back pain/sciatica risk,42,49,75
5,2,neck,32,180,80,8,0,0.63,2,1,7.80,Neck side bends,Neck strain,50,38,23
6,2,hand,32,180,80,8,0,0.48,2,1,3.00,nerve gliding,shoulder tendonitis,41,20,33
7,2,knee,32,180,80,8,0,0.44,2,1,5.20,mini squates,Prolonged standing,15,43,60
8,3,back,23,187,95,1,1,0.73,1,2,6.50,seated spinal twist,Low back pain,55,40,65
9,3,neck,23,187,95,1,0,0.60,1,2,5.50,Chin tucks,Cervicalgia,55,39,33
10,3,hand,23,187,95,1,0,0.33,1,2,2.00,Shoulder rolls,Shoulder Impingemnet,30,25,33
11,3,knee,23,187,95,1,0,0.33,1,2,2.00,Hip flexor stretches,Hip pain,5,34,80
12,4,back,25,168,65,1,1,0.68,2,2,5.00,seated spinal twist,Low back pain,55,40,65
13,4,neck,25,168,65,1,0,0.60,2,2,5.50,Chin tucks,Neck flexion,55,39,33
14,4,hand,25,168,65,1,0,0.33,2,2,2.00,Thoracic extension,Upper Back fatigue,30,25,33
15,4,knee,25,168,65,1,0,0.35,2,2,3.00,Hip flexor stretches,Hip pain,5,34,80
16,5,back,28,172,84,7,0,0.72,1,3,7.00,standing back extension,low back pain/sciatica risk,40,62,60
17,5,neck,28,172,84,7,0,0.59,1,3,6.75,Child’s pose,Neck strain,35,53,20
18,5,hand,28,172,84,7,1,0.39,1,3,4.00,Forearm stretch/Shoulder blade squeezes,shoulder tendonitis/Forearm Fatigue,30,37,20
19,5,knee,28,172,84,7,0,0.43,1,3,4.50,Calf raises,Circulatory fatigue,15,41,60
20,6,back,29,168,78,8,1,0.84,1,4,9.50,Cat-cow stretch,Herniated Disc Risk,40,26,20
21,6,neck,29,168,78,8,1,0.71,1,4,7.00,Neck rotation stretch,cervical strain,25,40,5
22,6,hand,29,168,78,8,0,0.36,1,4,2.25,wall angels,Shoulder Impingement,40,26,40
23,6,knee,29,168,78,8,0,0.46,1,4,3.50,Quadriceps stretch,Knee strain,55,40,50
24,7,back,40,170,64,14,1,0.84,2,4,9.75,Bridge Exercise,Herniated Disc Risk,40,26,20
25,7,neck,40,170,64,14,0,0.71,2,4,7.00,Neck rotation stretch,cervical strain,25,40,5
26,7,hand,40,170,64,14,0,0.36,2,4,2.75,wall angels,Shoulder Impingement,40,26,40
27,7,knee,40,170,64,14,0,0.46,2,4,4.00,Quadriceps stretch,Knee strain,55,40,50
28,8,back,23,180,55,2,1,0.77,1,5,7.50,Child’s pose,Low back pain,45,56,36
29,8,neck,23,180,55,2,0,0.45,1,5,3.25,thoracic rotation,Cervicalgia,19,51,25
30,8,hand,23,180,55,2,0,0.31,1,5,2.75,hip opener stretch,carpal tunnel syndrome,30,26,60
31,8,knee,23,180,55,2,0,0.60,1,5,9.00,mini squates,Knee osteoarthritis,95,50,40
32,9,back,31,181,80,7,0,0.79,2,5,6.25,Child’s pose,Low back pain,45,56,36
33,9,neck,31,181,80,7,0,0.48,2,5,3.50,thoracic rotation,Cervicalgia,19,51,25
34,9,hand,31,181,80,7,0,0.31,2,5,2.75,hip opener stretch,carpal tunnel syndrome,30,26,60
35,9,knee,31,181,80,7,0,0.55,2,5,7.00,mini squates,Knee osteoarthritis,95,50,40
36,10,back,35,172,83,13,1,0.75,1,6,8.50,Forward fold stretch,Low back pain,39,63,33
37,10,neck,35,172,83,13,0,0.50,1,6,6.75,Neck side bends,Neck strain,26,47,66
38,10,hand,35,172,83,13,0,0.30,1,6,4.75,shoulder shrugs,Forearm tendonitis,30,26,60
39,10,knee,35,172,83,13,1,0.49,1,6,7.00,standing hamstring stretch,leg fatigue,15,42,33
40,11,back,46,167,72,19,0,0.75,2,6,8.50,Forward fold stretch,Low back pain,39,63,33
41,11,neck,46,167,72,19,0,0.50,2,6,7.50,Neck side bends,Neck strain,26,47,66
42,11,hand,46,167,72,19,0,0.30,2,6,5.50,shoulder shrugs,Forearm tendonitis,30,26,60
43,11,knee,46,167,72,19,0,0.49,2,6,7.00,standing hamstring stretch,leg fatigue,15,42,33
44,12,back,30,170,65,8,1,0.57,1,7,6.00,Cat-cow stretch,Low back pain,42,44,82
45,12,neck,30,170,65,8,0,0.56,1,7,5.00,Neck rotation stretch,Neck strain,32,50,82
46,12,hand,30,170,65,8,0,0.28,1,7,2.25,chest opener stretch,Shoulder Impingement,30,20,33
47,12,knee,30,170,65,8,0,0.37,1,7,3.00,mini squates,Prolonged standing,10,36,82
48,13,back,46,167,72,19,0,0.57,2,7,7.00,Cat-cow stretch,Low back pain,42,44,82
49,13,neck,46,167,72,19,0,0.56,2,7,6.00,Neck rotation stretch,Neck strain,32,50,82
50,13,hand,46,167,72,19,0,0.28,2,7,3.25,Doorway pec stretch/shoulder external rotation,carpal tunnel syndrome,30,20,33
51,13,knee,46,167,72,19,0,0.37,2,7,4.25,mini squates,Prolonged standing,10,36,82

In [10]:
data.dtypes

worker ID              int64
Body part             object
age                    int64
hight                  int64
weight                 int64
work experince         int64
medical record         int64
Station risk         float64
shift                  int64
station                int64
final risk           float64
corrective action     object
problem               object
operation              int64
environment            int64
job frequency          int64
dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in data.select_dtypes(include=['object', 'category']).columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

In [13]:
data

,worker ID,Body part,age,hight,weight,work experince,medical record,Station risk,shift,station,final risk,corrective action,problem,operation,environment,job frequency
0,1,0,31,175,58,8,0,0.69,1,1,7.75,9,17,42,49,75
1,1,5,31,175,58,8,0,0.63,1,1,7.75,12,9,50,38,23
2,1,3,31,175,58,8,0,0.48,1,1,3.00,25,18,41,20,33
3,1,4,31,175,58,8,0,0.44,1,1,5.00,18,10,15,43,60
4,2,1,32,180,80,8,1,0.69,2,1,8.00,3,17,42,49,75
5,2,5,32,180,80,8,0,0.63,2,1,7.80,12,9,50,38,23
6,2,3,32,180,80,8,0,0.48,2,1,3.00,19,18,41,20,33
7,2,4,32,180,80,8,0,0.44,2,1,5.20,18,10,15,43,60
8,3,1,23,187,95,1,1,0.73,1,2,6.50,20,7,55,40,65
9,3,5,23,187,95,1,0,0.60,1,2,5.50,5,0,55,39,33
10,3,3,23,187,95,1,0,0.33,1,2,2.00,14,12,30,25,33
11,3,4,23,187,95,1,0,0.33,1,2,2.00,10,4,5,34,80
12,4,1,25,168,65,1,1,0.68,2,2,5.00,20,7,55,40,65
13,4,5,25,168,65,1,0,0.60,2,2,5.50,5,8,55,39,33
14,4,3,25,168,65,1,0,0.33,2,2,2.00,15,13,30,25,33
15,4,4,25,168,65,1,0,0.35,2,2,3.00,10,4,5,34,80
16,5,1,28,172,84,7,0,0.72,1,3,7.00,22,17,40,62,60
17,5,5,28,172,84,7,0,0.59,1,3,6.75,4,9,35,53,20
18,5,3,28,172,84,7,1,0.39,1,3,4.00,7,19,30,37,20
19,5,4,28,172,84,7,0,0.43,1,3,4.50,1,1,15,41,60
20,6,1,29,168,78,8,1,0.84,1,4,9.50,2,3,40,26,20
21,6,5,29,168,78,8,1,0.71,1,4,7.00,11,15,25,40,5
22,6,3,29,168,78,8,0,0.36,1,4,2.25,25,11,40,26,40
23,6,4,29,168,78,8,0,0.46,1,4,3.50,13,6,55,40,50
24,7,1,40,170,64,14,1,0.84,2,4,9.75,0,3,40,26,20
25,7,5,40,170,64,14,0,0.71,2,4,7.00,11,15,25,40,5
26,7,3,40,170,64,14,0,0.36,2,4,2.75,25,11,40,26,40
27,7,4,40,170,64,14,0,0.46,2,4,4.00,13,6,55,40,50
28,8,1,23,180,55,2,1,0.77,1,5,7.50,4,7,45,56,36
29,8,5,23,180,55,2,0,0.45,1,5,3.25,24,0,19,51,25
30,8,3,23,180,55,2,0,0.31,1,5,2.75,17,14,30,26,60
31,8,4,23,180,55,2,0,0.60,1,5,9.00,18,5,95,50,40
32,9,1,31,181,80,7,0,0.79,2,5,6.25,4,7,45,56,36
33,9,5,31,181,80,7,0,0.48,2,5,3.50,24,0,19,51,25
34,9,3,31,181,80,7,0,0.31,2,5,2.75,17,14,30,26,60
35,9,4,31,181,80,7,0,0.55,2,5,7.00,18,5,95,50,40
36,10,1,35,172,83,13,1,0.75,1,6,8.50,8,7,39,63,33
37,10,5,35,172,83,13,0,0.50,1,6,6.75,12,9,26,47,66
38,10,3,35,172,83,13,0,0.30,1,6,4.75,21,2,30,26,60
39,10,4,35,172,83,13,1,0.49,1,6,7.00,23,16,15,42,33
40,11,1,46,167,72,19,0,0.75,2,6,8.50,8,7,39,63,33
41,11,5,46,167,72,19,0,0.50,2,6,7.50,12,9,26,47,66
42,11,3,46,167,72,19,0,0.30,2,6,5.50,21,2,30,26,60
43,11,4,46,167,72,19,0,0.49,2,6,7.00,23,16,15,42,33
44,12,1,30,170,65,8,1,0.57,1,7,6.00,2,7,42,44,82
45,12,5,30,170,65,8,0,0.56,1,7,5.00,11,9,32,50,82
46,12,3,30,170,65,8,0,0.28,1,7,2.25,16,11,30,20,33
47,12,4,30,170,65,8,0,0.37,1,7,3.00,18,10,10,36,82
48,13,2,46,167,72,19,0,0.57,2,7,7.00,2,7,42,44,82
49,13,5,46,167,72,19,0,0.56,2,7,6.00,11,9,32,50,82
50,13,3,46,167,72,19,0,0.28,2,7,3.25,6,14,30,20,33
51,13,4,46,167,72,19,0,0.37,2,7,4.25,18,10,10,36,82

In [52]:
label_encoders['Body part'].transform(['neck'])

array([5])

In [59]:
test_obj = [5, 28, 186, 78, 3, 1, 1, 1, 34, 20, 20]

In [60]:
x = data.drop(['worker ID', 'corrective action', 'problem', 'Station risk', 'final risk'], axis=1).to_numpy()
y = data['corrective action'].to_numpy()
x, y

(array([[  0,  31, 175,  58,   8,   0,   1,   1,  42,  49,  75],
        [  5,  31, 175,  58,   8,   0,   1,   1,  50,  38,  23],
        [  3,  31, 175,  58,   8,   0,   1,   1,  41,  20,  33],
        [  4,  31, 175,  58,   8,   0,   1,   1,  15,  43,  60],
        [  1,  32, 180,  80,   8,   1,   2,   1,  42,  49,  75],
        [  5,  32, 180,  80,   8,   0,   2,   1,  50,  38,  23],
        [  3,  32, 180,  80,   8,   0,   2,   1,  41,  20,  33],
        [  4,  32, 180,  80,   8,   0,   2,   1,  15,  43,  60],
        [  1,  23, 187,  95,   1,   1,   1,   2,  55,  40,  65],
        [  5,  23, 187,  95,   1,   0,   1,   2,  55,  39,  33],
        [  3,  23, 187,  95,   1,   0,   1,   2,  30,  25,  33],
        [  4,  23, 187,  95,   1,   0,   1,   2,   5,  34,  80],
        [  1,  25, 168,  65,   1,   1,   2,   2,  55,  40,  65],
        [  5,  25, 168,  65,   1,   0,   2,   2,  55,  39,  33],
        [  3,  25, 168,  65,   1,   0,   2,   2,  30,  25,  33],
        [  4,  25, 168,  65,   1,   0,   2,   2,   5,  34,  80],
        [  1,  28, 172,  84,   7,   0,   1,   3,  40,  62,  60],
        [  5,  28, 172,  84,   7,   0,   1,   3,  35,  53,  20],
        [  3,  28, 172,  84,   7,   1,   1,   3,  30,  37,  20],
        [  4,  28, 172,  84,   7,   0,   1,   3,  15,  41,  60],
        [  1,  29, 168,  78,   8,   1,   1,   4,  40,  26,  20],
        [  5,  29, 168,  78,   8,   1,   1,   4,  25,  40,   5],
        [  3,  29, 168,  78,   8,   0,   1,   4,  40,  26,  40],
        [  4,  29, 168,  78,   8,   0,   1,   4,  55,  40,  50],
        [  1,  40, 170,  64,  14,   1,   2,   4,  40,  26,  20],
        [  5,  40, 170,  64,  14,   0,   2,   4,  25,  40,   5],
        [  3,  40, 170,  64,  14,   0,   2,   4,  40,  26,  40],
        [  4,  40, 170,  64,  14,   0,   2,   4,  55,  40,  50],
        [  1,  23, 180,  55,   2,   1,   1,   5,  45,  56,  36],
        [  5,  23, 180,  55,   2,   0,   1,   5,  19,  51,  25],
        [  3,  23, 180,  55,   2,   0,   1,   5,  30,  26,  60],
        [  4,  23, 180,  55,   2,   0,   1,   5,  95,  50,  40],
        [  1,  31, 181,  80,   7,   0,   2,   5,  45,  56,  36],
        [  5,  31, 181,  80,   7,   0,   2,   5,  19,  51,  25],
        [  3,  31, 181,  80,   7,   0,   2,   5,  30,  26,  60],
        [  4,  31, 181,  80,   7,   0,   2,   5,  95,  50,  40],
        [  1,  35, 172,  83,  13,   1,   1,   6,  39,  63,  33],
        [  5,  35, 172,  83,  13,   0,   1,   6,  26,  47,  66],
        [  3,  35, 172,  83,  13,   0,   1,   6,  30,  26,  60],
        [  4,  35, 172,  83,  13,   1,   1,   6,  15,  42,  33],
        [  1,  46, 167,  72,  19,   0,   2,   6,  39,  63,  33],
        [  5,  46, 167,  72,  19,   0,   2,   6,  26,  47,  66],
        [  3,  46, 167,  72,  19,   0,   2,   6,  30,  26,  60],
        [  4,  46, 167,  72,  19,   0,   2,   6,  15,  42,  33],
        [  1,  30, 170,  65,   8,   1,   1,   7,  42,  44,  82],
        [  5,  30, 170,  65,   8,   0,   1,   7,  32,  50,  82],
        [  3,  30, 170,  65,   8,   0,   1,   7,  30,  20,  33],
        [  4,  30, 170,  65,   8,   0,   1,   7,  10,  36,  82],
        [  2,  46, 167,  72,  19,   0,   2,   7,  42,  44,  82],
        [  5,  46, 167,  72,  19,   0,   2,   7,  32,  50,  82],
        [  3,  46, 167,  72,  19,   0,   2,   7,  30,  20,  33],
        [  4,  46, 167,  72,  19,   0,   2,   7,  10,  36,  82]]),
 array([ 9, 12, 25, 18,  3, 12, 19, 18, 20,  5, 14, 10, 20,  5, 15, 10, 22,
         4,  7,  1,  2, 11, 25, 13,  0, 11, 25, 13,  4, 24, 17, 18,  4, 24,
        17, 18,  8, 12, 21, 23,  8, 12, 21, 23,  2, 11, 16, 18,  2, 11,  6,
        18]))

In [61]:
scaler = MinMaxScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)
x_scaled

array([[0.00000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
        0.00000, 0.41111, 0.67442, 0.90909],
       [1.00000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
        0.00000, 0.50000, 0.41860, 0.23377],
       [0.60000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
        0.00000, 0.40000, 0.00000, 0.36364],
       [0.80000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
        0.00000, 0.11111, 0.53488, 0.71429],
       [0.20000, 0.39130, 0.65000, 0.62500, 0.38889, 1.00000, 1.00000,
        0.00000, 0.41111, 0.67442, 0.90909],
       [1.00000, 0.39130, 0.65000, 0.62500, 0.38889, 0.00000, 1.00000,
        0.00000, 0.50000, 0.41860, 0.23377],
       [0.60000, 0.39130, 0.65000, 0.62500, 0.38889, 0.00000, 1.00000,
        0.00000, 0.40000, 0.00000, 0.36364],
       [0.80000, 0.39130, 0.65000, 0.62500, 0.38889, 0.00000, 1.00000,
        0.00000, 0.11111, 0.53488, 0.71429],
       [0.20000, 0.00000, 1.00000, 1.00000, 0.00000, 1.00000, 0.00000,
        0.16667, 0.55556, 0.46512, 0.77922],
       [1.00000, 0.00000, 1.00000, 1.00000, 0.00000, 0.00000, 0.00000,
        0.16667, 0.55556, 0.44186, 0.36364],
       [0.60000, 0.00000, 1.00000, 1.00000, 0.00000, 0.00000, 0.00000,
        0.16667, 0.27778, 0.11628, 0.36364],
       [0.80000, 0.00000, 1.00000, 1.00000, 0.00000, 0.00000, 0.00000,
        0.16667, 0.00000, 0.32558, 0.97403],
       [0.20000, 0.08696, 0.05000, 0.25000, 0.00000, 1.00000, 1.00000,
        0.16667, 0.55556, 0.46512, 0.77922],
       [1.00000, 0.08696, 0.05000, 0.25000, 0.00000, 0.00000, 1.00000,
        0.16667, 0.55556, 0.44186, 0.36364],
       [0.60000, 0.08696, 0.05000, 0.25000, 0.00000, 0.00000, 1.00000,
        0.16667, 0.27778, 0.11628, 0.36364],
       [0.80000, 0.08696, 0.05000, 0.25000, 0.00000, 0.00000, 1.00000,
        0.16667, 0.00000, 0.32558, 0.97403],
       [0.20000, 0.21739, 0.25000, 0.72500, 0.33333, 0.00000, 0.00000,
        0.33333, 0.38889, 0.97674, 0.71429],
       [1.00000, 0.21739, 0.25000, 0.72500, 0.33333, 0.00000, 0.00000,
        0.33333, 0.33333, 0.76744, 0.19481],
       [0.60000, 0.21739, 0.25000, 0.72500, 0.33333, 1.00000, 0.00000,
        0.33333, 0.27778, 0.39535, 0.19481],
       [0.80000, 0.21739, 0.25000, 0.72500, 0.33333, 0.00000, 0.00000,
        0.33333, 0.11111, 0.48837, 0.71429],
       [0.20000, 0.26087, 0.05000, 0.57500, 0.38889, 1.00000, 0.00000,
        0.50000, 0.38889, 0.13953, 0.19481],
       [1.00000, 0.26087, 0.05000, 0.57500, 0.38889, 1.00000, 0.00000,
        0.50000, 0.22222, 0.46512, 0.00000],
       [0.60000, 0.26087, 0.05000, 0.57500, 0.38889, 0.00000, 0.00000,
        0.50000, 0.38889, 0.13953, 0.45455],
       [0.80000, 0.26087, 0.05000, 0.57500, 0.38889, 0.00000, 0.00000,
        0.50000, 0.55556, 0.46512, 0.58442],
       [0.20000, 0.73913, 0.15000, 0.22500, 0.72222, 1.00000, 1.00000,
        0.50000, 0.38889, 0.13953, 0.19481],
       [1.00000, 0.73913, 0.15000, 0.22500, 0.72222, 0.00000, 1.00000,
        0.50000, 0.22222, 0.46512, 0.00000],
       [0.60000, 0.73913, 0.15000, 0.22500, 0.72222, 0.00000, 1.00000,
        0.50000, 0.38889, 0.13953, 0.45455],
       [0.80000, 0.73913, 0.15000, 0.22500, 0.72222, 0.00000, 1.00000,
        0.50000, 0.55556, 0.46512, 0.58442],
       [0.20000, 0.00000, 0.65000, 0.00000, 0.05556, 1.00000, 0.00000,
        0.66667, 0.44444, 0.83721, 0.40260],
       [1.00000, 0.00000, 0.65000, 0.00000, 0.05556, 0.00000, 0.00000,
        0.66667, 0.15556, 0.72093, 0.25974],
       [0.60000, 0.00000, 0.65000, 0.00000, 0.05556, 0.00000, 0.00000,
        0.66667, 0.27778, 0.13953, 0.71429],
       [0.80000, 0.00000, 0.65000, 0.00000, 0.05556, 0.00000, 0.00000,
        0.66667, 1.00000, 0.69767, 0.45455],
       [0.20000, 0.34783, 0.70000, 0.62500, 0.33333, 0.00000, 1.00000,
        0.66667, 0.44444, 0.83721, 0.40260],
       [1.00000, 0.34783, 0.70000, 0.62500, 0.33333, 0.00000, 1.00000,
        0.66667, 0.15556, 0.72093, 0.25974],
       [0.60000, 0.34783, 0.70000, 0.62500, 0.33333, 0.00000, 1.00000,
        0.66667, 0.27778, 0.13953, 0.71429],
       [0.80000, 0.34783, 0.70000, 0.62500, 0.33333, 0.00000, 1.00000,
        0.66667, 1.00000, 0.69767, 0.45455],
       [0.20000, 0.52174, 0.25000, 0.70000, 0.66667, 1.00000, 0.00000,
        0.83333, 0.37778, 1.00000, 0.36364],
       [1.00000, 0.52174, 0.25000, 0.70000, 0.66667, 0.00000, 0.00000,
        0.83333, 0.23333, 0.62791, 0.79221],
       [0.60000, 0.52174, 0.25000, 0.70000, 0.66667, 0.00000, 0.00000,
        0.83333, 0.27778, 0.13953, 0.71429],
       [0.80000, 0.52174, 0.25000, 0.70000, 0.66667, 1.00000, 0.00000,
        0.83333, 0.11111, 0.51163, 0.36364],
       [0.20000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        0.83333, 0.37778, 1.00000, 0.36364],
       [1.00000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        0.83333, 0.23333, 0.62791, 0.79221],
       [0.60000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        0.83333, 0.27778, 0.13953, 0.71429],
       [0.80000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        0.83333, 0.11111, 0.51163, 0.36364],
       [0.20000, 0.30435, 0.15000, 0.25000, 0.38889, 1.00000, 0.00000,
        1.00000, 0.41111, 0.55814, 1.00000],
       [1.00000, 0.30435, 0.15000, 0.25000, 0.38889, 0.00000, 0.00000,
        1.00000, 0.30000, 0.69767, 1.00000],
       [0.60000, 0.30435, 0.15000, 0.25000, 0.38889, 0.00000, 0.00000,
        1.00000, 0.27778, 0.00000, 0.36364],
       [0.80000, 0.30435, 0.15000, 0.25000, 0.38889, 0.00000, 0.00000,
        1.00000, 0.05556, 0.37209, 1.00000],
       [0.40000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        1.00000, 0.41111, 0.55814, 1.00000],
       [1.00000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        1.00000, 0.30000, 0.69767, 1.00000],
       [0.60000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        1.00000, 0.27778, 0.00000, 0.36364],
       [0.80000, 1.00000, 0.00000, 0.42500, 1.00000, 0.00000, 1.00000,
        1.00000, 0.05556, 0.37209, 1.00000]])

In [62]:
model = RuleGenerator(
    with_reducts=True
)

In [63]:
model.fit(x, y, _)

RuleGenerator(with_reducts=True, apply_relabelling=False, relabelling_threshold=0.0, discard_uncertain_objects=False, add_uncovered_objects=True, certainty_threshold=0.0, print_nr_of_rule_candidates=False, print_changes=False, optimise_attribute_order=False, optimise_slopes=False, slope_options=None, covering_threshold=1e-06, inclusion_threshold=0.999999, priors_influence=0, approximation=None, inclusion_measure=None, attribute_ordering=None)

In [64]:
model.get_rules()

array([Rule(antecedent=array([0.00000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
              0.00000, 0.41111, 0.67442, 0.90909]), reducts=array([RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.6000000000000001, decision=9)                                       ,
       Rule(antecedent=array([1.00000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
              0.00000, 0.50000, 0.41860, 0.23377]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.4186046511627908, decision=12)                                    ,
       Rule(antecedent=array([0.60000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
              0.00000, 0.40000, 0.00000, 0.36364]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINANT, RelationTypes.UNUSED],
             dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.4186046511627908, decision=25)                                    ,
       Rule(antecedent=array([0.80000, 0.34783, 0.40000, 0.07500, 0.38889, 0.00000, 0.00000,
              0.00000, 0.11111, 0.53488, 0.71429]), reducts=array([RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.48051948051948057, decision=18)                                                           ,
       Rule(antecedent=array([0.20000, 0.39130, 0.65000, 0.62500, 0.38889, 1.00000, 1.00000,
              0.00000, 0.41111, 0.67442, 0.90909]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.5999999999999996, decision=3)                                    ,
       Rule(antecedent=array([1.00000, 0.39130, 0.65000, 0.62500, 0.38889, 0.00000, 1.00000,
              0.00000, 0.50000, 0.41860, 0.23377]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.4186046511627908, decision=12)                                  ,
       Rule(antecedent=array([0.60000, 0.39130, 0.65000, 0.62500, 0.38889, 0.00000, 1.00000,
              0.00000, 0.40000, 0.00000, 0.36364]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINANT, RelationTypes.UNUSED],
             dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.4186046511627908, decision=19)              ,
       Rule(antecedent=array([0.80000, 0.39130, 0.65000, 0.62500, 0.38889, 0.00000, 1.00000,
              0.00000, 0.11111, 0.53488, 0.71429]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINATED, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.48051948051948057, decision=18)                                  ,
       Rule(antecedent=array([0.20000, 0.00000, 1.00000, 1.00000, 0.00000, 1.00000, 0.00000,
              0.16667, 0.55556, 0.46512, 0.77922]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINATED,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.75, decision=20)                                                                    ,
       Rule(antecedent=array([1.00000, 0.00000, 1.00000, 1.00000, 0.00000, 0.00000, 0.00000,
              0.16667, 0.55556, 0.44186, 0.36364]), reducts=array([RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.INDISCERNIBLE,
              RelationTypes.UNUSED, RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.3999999999999999, decision=5)                                                       ,
       Rule(antecedent=array([0.60000, 0.00000, 1.00000, 1.00000, 0.00000, 0.00000, 0.00000,
              0.16667, 0.27778, 0.11628, 0.36364]), reducts=array([RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.3999999999999999, decision=14)                                  ,
       Rule(antecedent=array([0.80000, 0.00000, 1.00000, 1.00000, 0.00000, 0.00000, 0.00000,
              0.16667, 0.00000, 0.32558, 0.97403]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINATED,
              RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.6103896103896105, decision=10)                                                         ,
       Rule(antecedent=array([0.20000, 0.08696, 0.05000, 0.25000, 0.00000, 1.00000, 1.00000,
              0.16667, 0.55556, 0.46512, 0.77922]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINATED, RelationTypes.DOMINATED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.5999999999999996, decision=20)                                      ,
       Rule(antecedent=array([1.00000, 0.08696, 0.05000, 0.25000, 0.00000, 0.00000, 1.00000,
              0.16667, 0.55556, 0.44186, 0.36364]), reducts=array([RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT],
             dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.3999999999999999, decision=5)                  ,
       Rule(antecedent=array([0.60000, 0.08696, 0.05000, 0.25000, 0.00000, 0.00000, 1.00000,
              0.16667, 0.27778, 0.11628, 0.36364]), reducts=array([RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT],
             dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.3999999999999999, decision=15)                ,
       Rule(antecedent=array([0.80000, 0.08696, 0.05000, 0.25000, 0.00000, 0.00000, 1.00000,
              0.16667, 0.00000, 0.32558, 0.97403]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINANT, RelationTypes.DOMINATED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.5999999999999996, decision=10)                                      ,
       Rule(antecedent=array([0.20000, 0.21739, 0.25000, 0.72500, 0.33333, 0.00000, 0.00000,
              0.33333, 0.38889, 0.97674, 0.71429]), reducts=array([RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.6000000000000001, decision=22)                                                         ,
       Rule(antecedent=array([1.00000, 0.21739, 0.25000, 0.72500, 0.33333, 0.00000, 0.00000,
              0.33333, 0.33333, 0.76744, 0.19481]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.3896103896103895, decision=4)                                                            ,
       Rule(antecedent=array([0.60000, 0.21739, 0.25000, 0.72500, 0.33333, 1.00000, 0.00000,
              0.33333, 0.27778, 0.39535, 0.19481]), reducts=array([RelationTypes.INDISCERNIBLE, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.3999999999999999, decision=7)                                 ,
       Rule(antecedent=array([0.80000, 0.21739, 0.25000, 0.72500, 0.33333, 0.00000, 0.00000,
              0.33333, 0.11111, 0.48837, 0.71429]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.DOMINANT,
              RelationTypes.DOMINANT, RelationTypes.INDISCERNIBLE,
              RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.34883720930232565, decision=1)                                      ,
       Rule(antecedent=array([0.20000, 0.26087, 0.05000, 0.57500, 0.38889, 1.00000, 0.00000,
              0.50000, 0.38889, 0.13953, 0.19481]), reducts=array([RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.40000000000000013, decision=2)                                                          ,
       Rule(antecedent=array([1.00000, 0.26087, 0.05000, 0.57500, 0.38889, 1.00000, 0.00000,
              0.50000, 0.22222, 0.46512, 0.00000]), reducts=array([RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.36363636363636365, decision=11)                                 ,
       Rule(antecedent=array([0.60000, 0.26087, 0.05000, 0.57500, 0.38889, 0.00000, 0.00000,
              0.50000, 0.38889, 0.13953, 0.45455]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINANT, RelationTypes.DOMINANT,
              RelationTypes.INDISCERNIBLE, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.32558139534883723, decision=25)                                                       ,
       Rule(antecedent=array([0.20000, 0.73913, 0.15000, 0.22500, 0.72222, 1.00000, 1.00000,
              0.50000, 0.38889, 0.13953, 0.19481]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINATED, RelationTypes.DOMINATED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.7142857142857144, decision=0)                                     ,
       Rule(antecedent=array([1.00000, 0.73913, 0.15000, 0.22500, 0.72222, 0.00000, 1.00000,
              0.50000, 0.22222, 0.46512, 0.00000]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.36363636363636365, decision=11)                                                       ,
       Rule(antecedent=array([0.60000, 0.73913, 0.15000, 0.22500, 0.72222, 0.00000, 1.00000,
              0.50000, 0.38889, 0.13953, 0.45455]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED,
              RelationTypes.DOMINANT, RelationTypes.UNUSED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.32558139534883723, decision=25)                                                       ,
       Rule(antecedent=array([0.80000, 0.73913, 0.15000, 0.22500, 0.72222, 0.00000, 1.00000,
              0.50000, 0.55556, 0.46512, 0.58442]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.UNUSED, RelationTypes.INDISCERNIBLE,
              RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE,
              RelationTypes.DOMINATED], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.32558139534883723, decision=13)                                   ,
       Rule(antecedent=array([0.20000, 0.00000, 0.65000, 0.00000, 0.05556, 1.00000, 0.00000,
              0.66667, 0.44444, 0.83721, 0.40260]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINANT,
              RelationTypes.UNUSED, RelationTypes.DOMINATED,
              RelationTypes.UNUSED, RelationTypes.UNUSED, RelationTypes.UNUSED,
              RelationTypes.DOMINATED, RelationTypes.DOMINANT], dtype=object), slopes=array([1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000,
              1.00000, 1.00000, 1.00000, 1.00000]), credibility=0.5974025974025976, decision=4)                                                            ,
       Rule(antecedent=array([1.00000, 0.00000, 0.65000, 0.00000, 0.05556, 0.00000, 0.00000,
              0.66667, 0.15556, 0.72093, 0.25974]), reducts=array([RelationTypes.UNUSED, RelationTypes.UNUSED,

In [57]:
model.predict([test_obj])

array([20])

In [58]:
label_encoders['corrective action'].inverse_transform([model.predict([test_obj])
])

/Users/henri/Library/CloudStorage/OneDrive-Personal/Documents/_Work/PhD Thesis/2022-fuzzylem/venv/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:155: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array(['seated spinal twist'], dtype=object)

In [39]:
x.shape

(52, 11)

In [32]:
from fuzzyroughrules.full_inclusion_frri import GranularRuleGenerator
from fuzzyroughrules.rule_induction_base import RuleGenerator
from fuzzyroughrules.approximations import MulticlassMSECVXApproximation
from fuzzyroughrules.operators import StrictFuzzyInclusion
from pathlib import Path

gran_model = RuleGenerator(
    approximation=MulticlassMSECVXApproximation(),
    inclusion_measure=StrictFuzzyInclusion(),
    apply_relabelling=True,
    covering_threshold=.50 - 1e-6,
)

In [33]:
from hhelper.data_loader import get_dataset

x, y = get_dataset(Path.cwd() / 'keel-data' / 'ecoli-10-fold', '1tra')
x_test, y_test = get_dataset(Path.cwd() / 'keel-data' / 'ecoli-10-fold', '1tst')

In [37]:
gran_model.fit(x, y, _)

1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]
[0.66113 0.54686 0.69235 0.63620 0.56280 0.68209 0.69308 0.65748 0.64756
 0.65503 0.54586 0.52873 0.61189 0.71264 0.57367 0.55157 0.53448 0.58405]
6
[251, 252, 253, 254]
[0.76768 0.92509 0.88015 0.84848]
7
[255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301]
[0.53817 0.67039 0.54562 0.68906 0.51147 0.59108 0.50757 0.52170 0.49365
 0.61566 0.65257 0.58678 0.62202 0.29281 0.43184 0.52317 0.63496 0.66595
 0.66595 0.58199 0.71740 0.63559 0.67078 0.59002 0.70456 0.53180 0.51075
 0.56220 0.56948 0.48293 0.59260 0.51683 0.57653 0.63804 0.61434 0.60920
 0.63630 0.37972 0.64831 0.47959 0.53448 0.43711 0.51126 0.49384 0.46046
 0.48686 0.63628]
1
[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197]
[0.85132 0.41513 0.57938 0.75611 0.66450 0.69111 0.68648 0.61091 0.55461
 0.55114 0.74143 0.55161 0.45678 0.69747 0.62644 0.61425 0.52949 0.62055
 0.67888 0.57961 0.61530 0.64234 0.63932 0.76340 0.50518 0.78810 0.65351
 0.61159 0.54362 0.57778 0.57659 0.51321 0.45190 0.59110 0.78538 0.80524
 0.35978 0.62985 0.69747 0.50041 0.69747 0.52213 0.58020 0.59902 0.67549
 0.58427 0.54598 0.52165 0.52024 0.73044 0.67549 0.53890 0.59857 0.63154
 0.62055 0.63483 0.62569 0.65585 0.63154 0.55531 0.54408 0.63777 0.62128
 0.70846 0.57659 0.57659 0.51066 0.51310 0.62877 0.63946]
2
[199, 200]
[0.99992 0.71264]
3
[198]
[0.58683]
4
[201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232]
[0.54683 0.56828 0.61323 0.64633 0.55273 0.61307 0.50404 0.55763 0.54598
 0.51114 0.62644 0.56856 0.55409 0.61140 0.49255 0.55114 0.50016 0.71951
 0.59827 0.61323 0.61200 0.63483 0.60238 0.58427 0.61616 0.58867 0.69154
 0.48583 0.62965 0.64898 0.47434 0.58131]
5
[233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250]

GranularRuleGenerator(with_reducts=True, apply_relabelling=True, relabelling_threshold=0.0, discard_uncertain_objects=False, add_uncovered_objects=True, certainty_threshold=0.0, print_nr_of_rule_candidates=False, print_changes=False, optimise_attribute_order=False, optimise_slopes=False, slope_options=None, covering_threshold=0.499999, inclusion_threshold=0.999999, priors_influence=0, use_gran_approx=False, approximation=MulticlassMSECVXApproximation(weights=None, nn_approx=-1, n_jobs=None), inclusion_measure=<fuzzyroughrules.operators.StrictFuzzyInclusion object at 0x31d230340>, attribute_ordering=None)

In [38]:
gran_model.predict(x_test)

array([' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' cp',
       ' cp', ' cp', ' cp', ' cp', ' cp', ' cp', ' im', ' cp', ' im',
       ' im', ' im', ' im', ' im', ' im', ' im', ' im', ' im', ' pp',
       ' cp', ' omL', ' cp', ' cp', ' pp', ' pp', ' pp'], dtype=object)

In [39]:
model2.get_rules_as_string()

["[{'attribute': 2, 'type': 'l', 'bounds': [66.0]}, {'attribute': 7, 'type': 'l', 'bounds': [36.4]}], class: 1",
 "[{'attribute': 0, 'type': 'r', 'bounds': [7.565217391304348]}, {'attribute': 1, 'type': 'r', 'bounds': [187.0]}], class: 0"]

In [23]:
model2.selected_indexes

array([1, 4])

In [37]:
from fuzzyroughrules.approximations import LowerApproximation

appr = LowerApproximation()
pos_reg = appr.get_approximation(x_scaled, y)

In [38]:
pos_reg

array([0.93478, 0.60000, 0.58809, 0.58809, 0.94565, 0.89130, 0.91667])

Stap per stap berekening van appr.get_approximation(x_scaled, y)

In [42]:
from fuzzyroughrules.fuzzy_operators import triangular_similarity, discernibility_matrix, get_ind_low_apr, lukasiewicz_implicator

rel_mat = triangular_similarity(x_scaled, x_scaled)

In [43]:
rel_mat

array([[1.00000, 0.00000, 0.00000, 0.06522, 0.04255, 0.36397, 0.60000],
       [0.00000, 1.00000, 0.40000, 0.45000, 0.00000, 0.00000, 0.08333],
       [0.00000, 0.40000, 1.00000, 0.41191, 0.12500, 0.12500, 0.00654],
       [0.06522, 0.45000, 0.41191, 1.00000, 0.05435, 0.10870, 0.00000],
       [0.04255, 0.00000, 0.12500, 0.05435, 1.00000, 0.00000, 0.00000],
       [0.36397, 0.00000, 0.12500, 0.10870, 0.00000, 1.00000, 0.19485],
       [0.60000, 0.08333, 0.00654, 0.00000, 0.00000, 0.19485, 1.00000]])

In [44]:
fuzzy_set = discernibility_matrix(y, y)

In [45]:
fuzzy_set

array([[1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 1]])

In [47]:
impl = lukasiewicz_implicator(rel_mat, fuzzy_set)
impl

array([[1.00000, 1.00000, 1.00000, 0.93478, 1.00000, 1.00000, 1.00000],
       [1.00000, 1.00000, 0.60000, 1.00000, 1.00000, 1.00000, 0.91667],
       [1.00000, 0.60000, 1.00000, 0.58809, 1.00000, 1.00000, 1.00000],
       [0.93478, 1.00000, 0.58809, 1.00000, 0.94565, 0.89130, 1.00000],
       [1.00000, 1.00000, 1.00000, 0.94565, 1.00000, 1.00000, 1.00000],
       [1.00000, 1.00000, 1.00000, 0.89130, 1.00000, 1.00000, 1.00000],
       [1.00000, 0.91667, 1.00000, 1.00000, 1.00000, 1.00000, 1.00000]])

In [51]:
np.min(impl, 0)

array([0.93478, 0.60000, 0.58809, 0.58809, 0.94565, 0.89130, 0.91667])

Voor sectie 3.3 Rule selection

In [82]:
from fuzzyroughrules.fuzzy_operators import lukasiewicz_t_norm
from fuzzyroughrules.operators import triangular_relation

covering = np.zeros((model.n_samples, model.n_samples))
for i in range(model.n_samples):
    current_covering = lukasiewicz_t_norm(
        # fo.general_triangular_relation(self.X_scaled, self.X_scaled[i], self.theta, self.reducts[i]),
        triangular_relation(
            model.X_scaled,
            model.X_scaled[i],
            model.slopes[i],
            model.reducts[i]
        ),
        model.positive_region[i]
    )
    if len(current_covering.shape) > 1:
        current_covering = current_covering.T
    covering[i, :] = (1 * (current_covering > model.covering_threshold))

In [83]:
model.covering_threshold

1e-06

In [84]:
covering

array([[1.00000, 0.00000, 1.00000, 0.00000, 0.00000, 1.00000, 1.00000],
       [0.00000, 1.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 0.00000, 1.00000],
       [0.00000, 1.00000, 0.00000, 1.00000, 0.00000, 0.00000, 0.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 1.00000, 1.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 1.00000, 1.00000],
       [1.00000, 0.00000, 1.00000, 0.00000, 1.00000, 1.00000, 1.00000]])

In [81]:
from fuzzyroughrules.operators import RelationTypes

lukasiewicz_t_norm(
    triangular_relation(
        x_scaled[3],
        x_scaled[0], 
        slopes=np.ones(model.n_attributes, dtype=float),
        rel_types=np.array([RelationTypes.UNUSED, RelationTypes.DOMINANT, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE, RelationTypes.INDISCERNIBLE])
    ),
    model.positive_region[0]
)

array([0.00000])

In [80]:
model.reducts

array([[<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINANT: -1>,
        <RelationTypes.DOMINANT: -1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINATED: 1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.DOMINATED: 1>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINANT: -1>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINATED: 1>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINATED: 1>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.DOMINANT: -1>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.DOMINANT: -1>, <RelationTypes.DOMINANT: -1>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINANT: -1>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.DOMINANT: -1>],
       [<RelationTypes.UNUSED: 0>, <RelationTypes.DOMINANT: -1>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.UNUSED: 0>,
        <RelationTypes.UNUSED: 0>, <RelationTypes.DOMINANT: -1>]],
      dtype=object)

In [74]:
model.positive_region[0]

0.9347826086956521

In [58]:
model.inclusion_threshold

0.9999

In [62]:
model2.reducts

array([[ 0, -1, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0, -1,  0],
       [ 0,  0, -1,  0,  0,  0,  1,  0],
       [ 0,  1,  0,  0,  0,  0, -1,  0],
       [-1, -1,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0, -1],
       [ 0, -1,  0,  0,  0,  0,  0, -1]])